apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-admin
    receivers:
      - uid: email-admin-uid
        type: email
        settings:
          addresses: ${ADMIN_EMAIL}
          singleEmail: true
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: email-admin
    group_by:
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
